### ISSUE TITLE
Feature Request: ellipsis for truncated elements (not just center truncated)

### ISSUE THREAD

**Issue by adambundy** [polarblau/smarttruncation#1]
Great plugin! I would love to see an ellipsis on the far right end of my truncated elements. Thanks!

**Comment by adambundy** [comment]
Never mind. My container was too large and I didnt realize that it was doing this. </idiocy>

**Comment by polarblau** [comment]
Thanks! Right now the truncation can be slightly off depending on your font settings. I'm working on a test suite to improve this situation.
